[grpc]
addr = "0.0.0.0:50053"
enable_tls = false

[http]
addr = "0.0.0.0:8082"
enable_tls = false

enable_swagger = true
enable_web_admin = false
heartbeat_timeout = 180
cleanup_interval = 600
max_upload_bytes = 67108864

[web_admin]
addr = "0.0.0.0:8081"
enable_tls = false

[database]
db_type = "sled"
path = "./data/sms"
pool_size = 10
