[grpc]
addr = "0.0.0.0:50051"
enable_tls = false

[http]
addr = "0.0.0.0:8080"
enable_tls = false

enable_swagger = true
enable_web_admin = false
heartbeat_timeout = 120
cleanup_interval = 300
max_upload_bytes = 67108864

[web_admin]
addr = "0.0.0.0:8081"
enable_tls = false

[database]
db_type = "sled"
path = "./data/node-service.db"
pool_size = 10

[event_kv]
backend = "sled"
params = { path = "./data/events-sled.db" }

[logging]
level = "info"
format = "json"
file = "./logs/sms.log"
