name: SPEAR-TEST

on: push

jobs:
  Spear-build:
    name: make and run Spear DEMO
    runs-on: ubuntu-latest
    steps:
    - name: Read warehouse contents
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23' # 请根据需要选择合适的 Go 版本

    - name: Install flatbuffers
      run: |
        wget -q https://github.com/google/flatbuffers/releases/download/v24.12.23/Linux.flatc.binary.clang++-18.zip
        unzip Linux.flatc.binary.clang++-18.zip
        sudo cp flatc /usr/local/bin
        rm flatc Linux.flatc.binary.clang++-18.zip

    - name: Verify Go version
      run: go version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Verify Python version
      run: python --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Install dependencies and compile files
      run: |
        sudo apt install portaudio19-dev libx11-dev libxtst-dev
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        make

    - name: Set environment variables and run test program
      run: |
        ip_address=$(ip addr show eth0 | grep -oP 'inet \K[\d.]+')
        echo "IP Address: $ip_address"
        export SPEAR_RPC_ADDR=$ip_address
        echo "SPEAR_RPC_ADDR=$ip_address" >> $GITHUB_ENV
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        HUGGINGFACEHUB_API_TOKEN=${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        export HUGGINGFACEHUB_API_TOKEN=${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
        echo "SPEAR_RPC_ADDR=$ip_address" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "HUGGINGFACEHUB_API_TOKEN=${{ secrets.HUGGINGFACEHUB_API_TOKEN }}" >> $GITHUB_ENV
        go test -v ./test/simple_req_test.go
